### PR TITLE
Feat 117 ccf

### PR DESCRIPTION
**Pull request by saskiad**
working on CCF content.

This requires adding the .brainglobe asset to the capsule that builds this. See this notebook: https://codeocean.allenneuraldynamics.org/capsule/2209401/tree

### CODE REVIEW

**Review by d-w-liu — APPROVED** [review]
needs the addition of an `import os` to the first code block (I don't know why but it lets it build in jb)

the final input cell could probably use a `hide output` tag block to put it into a click to show/hide thing since the output is very long

**Review by d-w-liu — COMMENTED** [review]
needs the addition of an `import os` to the first code block (I don't know why but it lets `jb build` correctly build the page)

the final input cell could probably use a `hide output` tag block to put it into a click to show/hide thing since the output is very long

**Comment by saskiad** [comment]
check to make sure I did the hide output right- I assume it's simple?

**Review by d-w-liu — COMMENTED** [review]
Sorry, I should have included the full code that needs to be inserted to make the output toggleable. At the top of the cell, we need:

```
{
    "tags": [
        "hide-output"
    ]
}

**Review by d-w-liu — APPROVED** [review]

**Pull request merged**
